name: HelloWorld_First_CICD

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Choose the ENV'
        required: true
        options:
          - QUAL
          - INT
  push:
    branches:
        - main
  pull_request:
      branches:
        - main


jobs:
  choose_Env:
    runs-on: ubuntu-latest
    if: ${{ inputs.env == 'QUAL' }}
    steps:
      - uses: actions/checkout@v3
      - name: Helllo_world
        run: echo "Hello World"
        shell: bash
        
  job_name_Hello_2:
    runs-on: ubuntu-latest
    steps:
      - name: Step_Hello_world_2
        run: echo "Hello_world_2"
        shell: bash
