name: HelloWorld_First_CICD

on:
  push:
    branches:
        - main
  pull_request:
      branches:
        - main
  workflow_dispatch:
    inputs:
      env:
        description: 'Choose the ENV'
        required: true
        options:
          - QUAL
          - INT

if: ${{ inputs.env == 'QUAL' }}

jobs:
  hello_1: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Helllo_world
        run: echo "Hello World"
        shell: bash
  hello_2:
      runs-on: ubuntu-latest
      steps:
      - name: Step_Hello_world_2
        run: echo "Hello_world_2"
        shell: bash
  
