name: HelloWorld_First_CICD

on:
  push:
    branches:
        - main
  pull_request:
      branches:
        - main
  workflow_dispatch:


jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Start of job 1
        run: echo "Hello World"
        shell: bash
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Start Job 2
      run: echo "Starting Job 2"
  job3:
    runs-on: ubuntu-latest
    steps:
    - name: Start Job 3
      run: echo "Starting Job 3"
